//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebMB.Context
{
    using System;
    using System.Collections.Generic;
    
    public partial class ImportProduct
    {
        public int importID { get; set; }
        public int productID { get; set; }
        public int importQuantity { get; set; }
        public Nullable<System.DateTime> createDate { get; set; }
        public Nullable<System.DateTime> confirmDate { get; set; }
        public Nullable<int> status { get; set; }
    }
}
